services:
  api:
    build: api/
    command: python main.py
    ports:
      - 8000:8000

  bot:
    build: bot/
    command: python bot.py
    network_mode: host
    depends_on:
      - api